name: Environment

on: push

jobs:
  build-and-deploy:
        runs-on: ubuntu-latest
        
        permissions:
          deployments: write
        
        steps:
        - name: Checkout
          uses: actions/checkout@v1
          
        - name: Identify
          run: |
            git config --global user.name Bonee94
            git config --global user.email bonee94@yahoo.com

        - name: Build
          run:
            npm install
            
        - name: Deploy
          run: 
            npm run deploy
          env:
            REACT_APP_EMAIL_USER: ${{ secrets.REACT_APP_EMAIL_USER }}
            REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
            REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
            REACT_APP_REFRESH_TOKEN: ${{ secrets.REACT_APP_REFRESH_TOKEN }}
            REACT_APP_ACCESS_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }}
