name: Enviroment

on: push

jobs:
  build-and-deploy:
        runs-on: ubuntu-latest
        
        permissions:
          deployments: write
        
        steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Build
          run:
            npm install
            npm run build
          env:
            REACT_APP_EMAIL_USER: ${{ secrets.REACT_APP_EMAIL_USER }}
            REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
            REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
            REACT_APP_REFRESH_TOKEN: ${{ secrets.REACT_APP_REFRESH_TOKEN }}
            REACT_APP_ACCESS_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }}
            
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./build
